package dockerrunserver

import dockerrun.api.ContainerStatus
import dockerrun.embedded.DockerRunEmbedded
import foundation.url.protocol.Libp2pRpcProtocol
import org.json.JSONObject
import java.util.*

/**
 * Handles RPC requests for the Docker run service.
 *
 * The generated bytecode running in the client's SJVM sandbox makes RPC calls
 * back to this handler for all container operations.
 *
 * RPC Methods:
 *   health                -> "OK"
 *   __bytecode_request    -> Base64 JAR + class name
 *   startContainer        -> starts container, returns UUID
 *   getAllContainers       -> returns list of container UUIDs
 *   getContainer           -> returns container data
 *   pauseContainer         -> pauses a running container
 *   unpauseContainer       -> unpauses a paused container
 *   terminateContainer     -> terminates a container
 *   getImageReference      -> gets container image reference
 *   getEnvironmentVariables -> gets container env vars
 *   getStatus              -> gets container status
 *   getAutoTerminateSeconds -> gets auto-terminate duration
 *   getCreatedAt           -> gets creation timestamp
 *   getErrorMessage        -> gets error message if failed
 *   getDockerContainerId   -> gets Docker container ID
 */
class DockerRunRpcHandler(
    private val dockerRunService: DockerRunEmbedded,
    private val jarBytes: ByteArray,
    private val implClassName: String,
    private val stdlibJarBytes: ByteArray
) {

    fun handleRequest(request: Libp2pRpcProtocol.RpcRequest): Libp2pRpcProtocol.RpcResponse {
        return try {
            val result = dispatch(request.method, request.params)
            Libp2pRpcProtocol.RpcResponse.success(request.id, result)
        } catch (e: Exception) {
            println("[DockerRunServer] Error handling '${request.method}': ${e.message}")
            Libp2pRpcProtocol.RpcResponse.error(request.id, "-1", e.message ?: "Unknown error")
        }
    }

    fun handleP2pRequest(path: String, params: Map<String, Any?>): Any? {
        return dispatch(path, params)
    }

    private fun dispatch(method: String, params: Map<String, Any?>): Any? {
        return when (method) {
            "health" -> "OK"

            "__bytecode_request" -> {
                println("[DockerRunServer] Serving bytecode (impl: ${jarBytes.size} bytes, stdlib: ${stdlibJarBytes.size} bytes)")
                mapOf(
                    "jar" to Base64.getEncoder().encodeToString(jarBytes),
                    "className" to implClassName,
                    "stdlibJar" to Base64.getEncoder().encodeToString(stdlibJarBytes)
                )
            }

            "startContainer" -> {
                val imageReference = requireParam(params, "imageReference")
                val autoTerminateSeconds = (params["autoTerminateSeconds"]?.toString()?.toLongOrNull()) ?: 0L

                // Parse environment variables from params
                val envVars = mutableMapOf<String, String>()
                val envObj = params["environmentVariables"]
                if (envObj is Map<*, *>) {
                    for ((key, value) in envObj) {
                        if (key != null && value != null) {
                            envVars[key.toString()] = value.toString()
                        }
                    }
                }

                val container = dockerRunService.startContainer(imageReference, envVars, autoTerminateSeconds)
                mapOf("uuid" to container.uuid.toString())
            }

            "getAllContainers" -> {
                val containers = dockerRunService.getAllContainers()
                val uuidList = containers.map { it.uuid.toString() }
                mapOf("uuids" to uuidList)
            }

            "getContainer" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                val container = dockerRunService.getContainer(uuid)
                containerToMap(container)
            }

            "pauseContainer" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                val container = dockerRunService.getContainer(uuid)
                dockerRunService.pauseContainer(container)
                mapOf("paused" to true)
            }

            "unpauseContainer" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                val container = dockerRunService.getContainer(uuid)
                dockerRunService.unpauseContainer(container)
                mapOf("unpaused" to true)
            }

            "terminateContainer" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                val container = dockerRunService.getContainer(uuid)
                dockerRunService.terminateContainer(container)
                mapOf("terminated" to true)
            }

            "getImageReference" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                mapOf("imageReference" to dockerRunService.getContainer(uuid).imageReference)
            }

            "getEnvironmentVariables" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                val envVars = dockerRunService.getContainer(uuid).environmentVariables
                mapOf("environmentVariables" to envVars)
            }

            "getStatus" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                mapOf("status" to dockerRunService.getContainer(uuid).status.name)
            }

            "getAutoTerminateSeconds" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                mapOf("autoTerminateSeconds" to dockerRunService.getContainer(uuid).autoTerminateSeconds)
            }

            "getCreatedAt" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                mapOf("createdAt" to dockerRunService.getContainer(uuid).createdAt)
            }

            "getErrorMessage" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                mapOf("errorMessage" to dockerRunService.getContainer(uuid).errorMessage)
            }

            "getDockerContainerId" -> {
                val uuid = UUID.fromString(requireParam(params, "uuid"))
                mapOf("dockerContainerId" to dockerRunService.getContainer(uuid).dockerContainerId)
            }

            else -> {
                mapOf(
                    "service" to "url://dockerrun/",
                    "type" to "rpc",
                    "description" to "Remote Docker container management service implementing DockerRunApi",
                    "availableMethods" to listOf(
                        "startContainer(imageReference, environmentVariables, autoTerminateSeconds): returns {uuid}",
                        "getAllContainers(): returns {uuids: [...]}",
                        "getContainer(uuid): returns container data",
                        "pauseContainer(uuid): pauses a running container",
                        "unpauseContainer(uuid): unpauses a paused container",
                        "terminateContainer(uuid): terminates a container",
                        "getImageReference(uuid): returns {imageReference}",
                        "getEnvironmentVariables(uuid): returns {environmentVariables}",
                        "getStatus(uuid): returns {status}",
                        "getAutoTerminateSeconds(uuid): returns {autoTerminateSeconds}",
                        "getCreatedAt(uuid): returns {createdAt}",
                        "getErrorMessage(uuid): returns {errorMessage}",
                        "getDockerContainerId(uuid): returns {dockerContainerId}"
                    )
                )
            }
        }
    }

    private fun containerToMap(container: dockerrun.api.DockerContainer): Map<String, Any?> {
        return mapOf(
            "uuid" to container.uuid.toString(),
            "imageReference" to container.imageReference,
            "environmentVariables" to container.environmentVariables,
            "status" to container.status.name,
            "autoTerminateSeconds" to container.autoTerminateSeconds,
            "createdAt" to container.createdAt,
            "errorMessage" to container.errorMessage,
            "dockerContainerId" to container.dockerContainerId
        )
    }
}

private fun requireParam(params: Map<String, Any?>, name: String): String {
    return params[name]?.toString()
        ?: throw IllegalArgumentException(
            "Missing required parameter '$name'. Provided parameters: ${params.keys}"
        )
}
